// <auto-generated />
namespace TemplateApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class AddHourlyRate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHourlyRate));
        
        string IMigrationMetadata.Id
        {
            get { return "201312121150297_AddHourlyRate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
